import type { User, Company, Task, Submission, Evaluation, TaskTemplate, SubmissionContentType, EvaluationSchema, Activity } from './types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Alice Candidate',
    email: 'alice@example.com',
    role: 'candidate',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 30)).toISOString(),
    isActive: true,
    isVerified: true,
    profile: {
      avatarUrl: 'https://picsum.photos/seed/avatar1/100/100',
      bio: 'Aspiring frontend developer with a passion for React.',
      location: 'San Francisco, CA',
      experienceLevel: 'Intermediate',
      skills: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS'],
      githubUrl: 'https://github.com/alice-candidate',
      linkedinUrl: 'https://linkedin.com/in/alice-candidate',
    },
    candidatePerformance: {
      completedTasks: 2,
      averageScore: 92,
      ranking: 15,
    },
  },
  {
    id: 'user-2',
    name: 'Bob Company',
    email: 'bob@techcorp.com',
    role: 'company',
    companyId: 'company-1',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 60)).toISOString(),
    isActive: true,
    isVerified: true,
    profile: {
      avatarUrl: 'https://picsum.photos/seed/avatar2/100/100',
      bio: 'Hiring manager at TechCorp.',
    },
  },
  {
    id: 'user-3',
    name: 'Charlie Admin',
    email: 'charlie@skillmatch.pro',
    role: 'admin',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 120)).toISOString(),
    isActive: true,
    isVerified: true,
    profile: {
      avatarUrl: 'https://picsum.photos/seed/avatar3/100/100',
    },
  },
  {
    id: 'user-4',
    name: 'Diana Developer',
    email: 'diana@example.com',
    role: 'candidate',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString(),
    isActive: false, // Changed for testing
    isVerified: true,
    profile: {
      avatarUrl: 'https://picsum.photos/seed/avatar4/100/100',
      bio: 'Full-stack engineer with 5 years of experience.',
      location: 'New York, NY',
      experienceLevel: 'Advanced',
      skills: ['Node.js', 'Python', 'GraphQL', 'AWS'],
      githubUrl: 'https://github.com/diana-dev',
    },
    candidatePerformance: {
      completedTasks: 1,
      averageScore: 88,
      ranking: 23,
    },
  },
  {
    id: 'user-5',
    name: 'Ethan Employer',
    email: 'ethan@innovate.io',
    role: 'company',
    companyId: 'company-2',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 20)).toISOString(),
    isActive: true,
    isVerified: true,
    profile: {
      avatarUrl: 'https://picsum.photos/seed/avatar5/100/100',
      bio: 'Lead Recruiter at Innovate Inc.',
    },
  },
];

export const mockCompanies: Company[] = [
  {
    id: 'company-1',
    name: 'TechCorp',
    description: 'A leading innovator in cloud solutions.',
    ownerId: 'user-2',
    website: 'https://techcorp.com',
    logoUrl: 'https://picsum.photos/seed/company1/100/100',
    industry: 'Technology',
    location: 'Silicon Valley, CA',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 60)).toISOString(),
    isActive: true,
    isVerified: true,
  },
  {
    id: 'company-2',
    name: 'Innovate Inc.',
    description: 'Building the future of decentralized applications.',
    ownerId: 'user-5',
    website: 'https://innovate.io',
    logoUrl: 'https://picsum.photos/seed/company2/100/100',
    industry: 'FinTech',
    location: 'New York, NY',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 20)).toISOString(),
    isActive: true,
    isVerified: false,
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Build a Responsive Navbar Component',
    description: 'The goal of this task is to create a reusable and responsive navigation bar for a modern web application.',
    instructions: '1. Use React and Tailwind CSS.\n2. The navbar should have a logo, navigation links, and a call-to-action button.\n3. It must collapse into a hamburger menu on mobile screens (under 768px).\n4. The state of the mobile menu (open/closed) should be managed within the component.',
    expectedOutputs: 'A single React component file (.tsx) containing the Navbar. The component should be self-contained and ready to be used in a Next.js project. No external state management libraries should be used.',
    roleCategory: 'Engineering',
    taskTypes: ['Coding', 'Design'],
    difficulty: 'Intermediate',
    deadline: '2024-08-15T23:59:59Z',
    timeLimitMinutes: 120,
    companyId: 'company-1',
    createdBy: 'user-2',
    status: 'published',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 9)).toISOString(),
    multiRound: false,
  },
  {
    id: 'task-2',
    title: 'Design a Database Schema for a Blog',
    description: 'This task requires you to design a normalized database schema for a typical blogging platform.',
    instructions: '1. Identify the core entities: Users, Posts, Comments, and Tags.\n2. Define the attributes for each entity.\n3. Establish the relationships between entities (e.g., one-to-many, many-to-many).\n4. Provide the schema as a SQL CREATE TABLE script.',
    expectedOutputs: 'A single .sql file containing the SQL statements to create all necessary tables, columns, primary keys, and foreign keys.',
    roleCategory: 'Data',
    taskTypes: ['Documentation'],
    difficulty: 'Beginner',
    deadline: '2024-08-20T23:59:59Z',
    companyId: 'company-1',
    createdBy: 'user-2',
    status: 'published',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
    multiRound: false,
  },
  {
    id: 'task-3',
    title: 'Create a Serverless API Endpoint',
    description: 'Build a serverless function that acts as a proxy to a third-party API, adding caching to reduce latency.',
    instructions: '1. Choose a serverless provider (e.g., AWS Lambda, Vercel Functions).\n2. The function should accept a stock ticker symbol (e.g., "AAPL").\n3. It should fetch stock data from a free API like Alpha Vantage or Financial Modeling Prep.\n4. Cache the response for 5 minutes to avoid hitting API rate limits.\n5. Handle potential errors from the third-party API gracefully.',
    expectedOutputs: 'A link to a public GitHub repository containing your serverless function code and a brief README explaining how to deploy and test it.',
    roleCategory: 'Engineering',
    taskTypes: ['Coding'],
    difficulty: 'Advanced',
    deadline: '2024-08-25T23:59:59Z',
    companyId: 'company-2',
    createdBy: 'user-5',
    status: 'closed',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 15)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 14)).toISOString(),
    multiRound: false,
  },
  {
    id: 'task-4',
    title: 'Fullstack Project Challenge',
    description: 'A comprehensive challenge involving both frontend and backend development to build a mini-application.',
    instructions: '', // Empty for multi-round
    expectedOutputs: '', // Empty for multi-round
    roleCategory: 'Engineering',
    taskTypes: ['Coding', 'Project', 'Documentation'],
    difficulty: 'Expert',
    deadline: '2024-09-30T23:59:59Z',
    companyId: 'company-2',
    createdBy: 'user-5',
    status: 'published',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    multiRound: true,
    rounds: [
      {
        roundNumber: 1,
        instructions: 'Design and build the backend API. It should have endpoints for creating and retrieving user data. Use Node.js and Express.',
        expectedOutputs: 'A set of functional REST API endpoints deployed on a test server.',
        timeLimitMinutes: 180,
      },
      {
        roundNumber: 2,
        instructions: 'Build the frontend interface that consumes the API from Round 1. It should have a form to create a user and a table to display users.',
        expectedOutputs: 'A responsive single-page application built with React.',
        timeLimitMinutes: 240,
      },
    ],
  },
];

export const mockTemplates: TaskTemplate[] = [
  {
    templateId: 'TPL-ENG-001',
    title: 'Frontend Responsive Component',
    description: 'A standard task to create a reusable and responsive component for a modern web application.',
    instructions: '1. Use React and Tailwind CSS.\n2. Component should have standard elements like a header, content, and footer.\n3. It must be responsive across mobile, tablet, and desktop breakpoints.\n4. Manage state internally without external libraries.',
    expectedOutputs: 'A single React component file (.tsx) that is self-contained and ready for use.',
    roleCategory: 'Engineering',
    taskTypes: ['Coding', 'Design'],
    difficulty: 'Intermediate',
    timeLimitMinutes: 120,
    createdBy: 'company-1',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 40)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 40)).toISOString(),
    multiRound: false,
  },
  {
    templateId: 'TPL-DATA-001',
    title: 'Blog Database Schema Design',
    description: 'This task requires designing a normalized database schema for a typical blogging platform.',
    instructions: '1. Identify the core entities: Users, Posts, Comments, and Tags.\n2. Define attributes for each entity.\n3. Establish relationships (one-to-many, many-to-many).\n4. Provide the schema as a SQL CREATE TABLE script.',
    expectedOutputs: 'A single .sql file with SQL statements for tables, columns, PKs, and FKs.',
    roleCategory: 'Data',
    taskTypes: ['Documentation'],
    difficulty: 'Beginner',
    timeLimitMinutes: 60,
    createdBy: 'company-1',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 35)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 35)).toISOString(),
    multiRound: false,
  },
  {
    templateId: 'TPL-ENG-002',
    title: 'Fullstack Mini-App (2 Rounds)',
    description: 'A comprehensive challenge involving both frontend and backend development to build a mini-application.',
    instructions: '',
    expectedOutputs: '',
    roleCategory: 'Engineering',
    taskTypes: ['Coding', 'Project'],
    difficulty: 'Expert',
    createdBy: 'company-2',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 30)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 30)).toISOString(),
    multiRound: true,
    rounds: [
      { roundNumber: 1, instructions: 'Build the REST API for CRUD operations on a "notes" resource.', expectedOutputs: 'A GitHub repo with the backend code and a Postman collection.', timeLimitMinutes: 120 },
      { roundNumber: 2, instructions: 'Build a React frontend to consume the "notes" API.', expectedOutputs: 'A deployed frontend application link.', timeLimitMinutes: 180 },
    ],
  }
];

export const mockSubmissions: Submission[] = [
  {
    id: 'sub-1',
    taskId: 'task-1',
    userId: 'user-1',
    companyId: 'company-1',
    content: {
      type: 'link',
      value: 'https://github.com/alice-candidate/responsive-navbar',
    },
    status: 'shortlisted',
    assignedAt: '2024-08-09T10:00:00Z',
    submittedAt: '2024-08-10T10:00:00Z',
    lastUpdated: '2024-08-12T09:00:00Z',
  },
  {
    id: 'sub-2',
    taskId: 'task-1',
    userId: 'user-4',
    companyId: 'company-1',
    content: {
      type: 'link',
      value: 'https://github.com/diana-developer/navbar-project',
    },
    status: 'rejected',
    assignedAt: '2024-08-10T11:00:00Z',
    submittedAt: '2024-08-11T14:30:00Z',
    lastUpdated: '2024-08-12T11:00:00Z',
  },
  {
    id: 'sub-3',
    taskId: 'task-2',
    userId: 'user-1',
    companyId: 'company-1',
    status: 'resubmitted',
    assignedAt: '2024-08-11T09:00:00Z',
    submittedAt: '2024-08-12T09:00:00Z',
    resubmittedAt: '2024-08-13T11:00:00Z',
    lastUpdated: '2024-08-13T11:00:00Z',
    content: {
        type: 'externalLink',
        value: 'https://gist.github.com/alice-candidate/schema.sql',
    },
  },
  {
    id: 'sub-4',
    taskId: 'task-4',
    userId: 'user-1',
    companyId: 'company-2',
    status: 'in-progress',
    assignedAt: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
    lastUpdated: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
    currentRound: 1,
    attemptsCount: 1,
  },
   {
    id: 'sub-5',
    taskId: 'task-3',
    userId: 'user-1',
    companyId: 'company-2',
    status: 'assigned',
    assignedAt: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    lastUpdated: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    attemptsCount: 0,
  },
  {
    id: 'sub-6',
    taskId: 'task-2',
    userId: 'user-4',
    companyId: 'company-1',
    content: {
      type: 'file',
      value: '/mock-uploads/diana-schema.sql',
      fileName: 'diana-schema.sql',
      fileSize: 1536, // 1.5 KB
    },
    status: 'pending',
    assignedAt: new Date(new Date().setDate(new Date().getDate() - 4)).toISOString(),
    submittedAt: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
    lastUpdated: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
  },
];

export const mockEvaluations: Evaluation[] = [
  {
    id: 'eval-1',
    submissionId: 'sub-1',
    score: 84,
    criteriaScores: {
      'Proficiency': 9,
      'Best Practices': 8,
      'Clarity': 9,
      'Documentation': 7,
      'Analysis': 8,
      'Solution Quality': 9,
      'Innovation': 8,
      'Polish & Initiative': 9,
      'Collaboration': 8,
      'Proactiveness': 9,
    },
    criteriaComments: {
        'Proficiency': 'Great command of React hooks and state management.',
        'Best Practices': 'Code is clean and follows conventions. Could add more tests.',
        'Clarity': 'The video explanation was clear and concise.',
        'Documentation': 'The README was good, but could be more detailed.',
        'Analysis': 'Good breakdown of the problem.',
        'Solution Quality': 'The solution is robust and handles edge cases.',
        'Innovation': 'Nice use of a custom hook to abstract logic.',
        'Polish & Initiative': 'The UI is polished and looks great.',
        'Collaboration': 'Seems like they would be a great team player.',
        'Proactiveness': 'Showed initiative by adding a dark mode toggle.',
    },
    feedback:
      'Excellent work! The component is well-structured and fully responsive. Great use of Tailwind CSS variants. Consider adding ARIA attributes for better accessibility.',
    evaluatedBy: 'user-2',
    evaluatedAt: '2024-08-11T18:00:00Z',
  },
  {
    id: 'eval-2',
    submissionId: 'sub-3',
    score: 75,
    criteriaScores: {
        'Proficiency': 7,
        'Best Practices': 8,
        'Clarity': 9,
        'Documentation': 6,
        'Analysis': 9,
        'Solution Quality': 7,
        'Innovation': 6,
        'Polish & Initiative': 7,
        'Collaboration': 8,
        'Proactiveness': 8,
    },
    criteriaComments: {
        'Proficiency': 'Good understanding of SQL basics.',
        'Best Practices': 'The schema is normalized, which is good.',
        'Clarity': 'The explanation was easy to follow.',
        'Documentation': 'Could use more comments in the SQL file.',
        'Analysis': 'Correctly identified the main entities.',
        'Solution Quality': 'The main issue was the many-to-many relationship handling.',
        'Innovation': 'Standard approach, which is fine for this task.',
        'Polish & Initiative': 'The submission was clean and to the point.',
        'Collaboration': 'N/A',
        'Proactiveness': 'N/A',
    },
    feedback:
      'The SQL script is mostly correct, but the relationship between Posts and Tags should be many-to-many, requiring a join table. The schema is otherwise well-defined.',
    evaluatedBy: 'user-2',
    evaluatedAt: '2024-08-12T15:00:00Z',
  },
  {
    id: 'eval-3',
    submissionId: 'sub-2',
    score: 65,
    criteriaScores: {
      'Proficiency': 7,
      'Best Practices': 6,
      'Clarity': 8,
      'Documentation': 5,
      'Analysis': 7,
      'Solution Quality': 6,
      'Innovation': 5,
      'Polish & Initiative': 7,
      'Collaboration': 8,
      'Proactiveness': 6,
    },
    criteriaComments: {},
    feedback:
      'The submission was okay, but did not meet all requirements. The mobile view was not fully responsive.',
    evaluatedBy: 'user-2',
    evaluatedAt: '2024-08-12T10:00:00Z',
  },
];

export const mockEvaluationSchemas: EvaluationSchema[] = [
    {
        id: 'schema-1',
        name: 'Standard Technical Evaluation',
        description: 'A balanced schema for evaluating core technical roles.',
        isActive: true,
        criteria: [
            { id: 'crit-1-1', name: 'Technical Skills', description: 'Assesses mastery of required technologies and tools.', maxPoints: 10 },
            { id: 'crit-1-2', name: 'Problem Solving', description: 'Evaluates the ability to analyze problems and devise effective solutions.', maxPoints: 10 },
            { id: 'crit-1-3', name: 'Code Quality', description: 'Reviews code for readability, structure, and best practices.', maxPoints: 10 },
            { id: 'crit-1-4', name: 'Communication', description: 'Judges the clarity of explanations and thought process.', maxPoints: 10 },
        ],
    },
    {
        id: 'schema-2',
        name: 'Frontend Specialist Evaluation',
        description: 'A schema focused on frontend-specific skills and user experience.',
        isActive: false,
        criteria: [
            { id: 'crit-2-1', name: 'React Proficiency', description: 'Correct use of hooks, components, and state management.', maxPoints: 10 },
            { id: 'crit-2-2', name: 'UI/UX Implementation', description: 'Attention to detail in implementing the design.', maxPoints: 10 },
            { id: 'crit-2-3', name: 'Responsiveness', description: 'How well the solution adapts to different screen sizes.', maxPoints: 10 },
            { id: 'crit-2-4', name: 'Performance', description: 'Efficiency of the code and awareness of rendering performance.', maxPoints: 10 },
        ],
    },
    {
        id: 'schema-3',
        name: 'Soft Skills Assessment',
        description: 'Focuses on non-technical aspects like communication and teamwork.',
        isActive: true,
        criteria: [
            { id: 'crit-3-1', name: 'Clarity of Communication', description: 'How clearly ideas are presented.', maxPoints: 10 },
            { id: 'crit-3-2', name: 'Proactiveness', description: 'Did the candidate ask clarifying questions or suggest improvements?', maxPoints: 10 },
            { id: 'crit-3-3', name: 'Presentation', description: 'The overall quality and polish of the submission.', maxPoints: 10 },
        ],
    },
];

export const mockActivityLogs: Activity[] = [
  {
    id: 'log-1',
    performerId: 'user-1',
    actionType: 'submission',
    timestamp: '2024-08-10T10:00:00Z',
    targetEntity: { type: 'Submission', id: 'sub-1', name: 'Responsive Navbar' },
    status: 'Success',
    description: 'Alice Candidate submitted work for "Build a Responsive Navbar Component".'
  },
  {
    id: 'log-2',
    performerId: 'user-2',
    actionType: 'status_change',
    timestamp: '2024-08-12T09:00:00Z',
    targetEntity: { type: 'Submission', id: 'sub-1', name: 'Responsive Navbar' },
    status: 'Success',
    description: 'Bob Company changed status to Shortlisted for submission sub-1.'
  },
  {
    id: 'log-3',
    performerId: 'user-3',
    actionType: 'override',
    timestamp: new Date(new Date().setHours(new Date().getHours() - 2)).toISOString(),
    targetEntity: { type: 'Submission', id: 'sub-2', name: 'Navbar Project' },
    status: 'Success',
    description: 'Charlie Admin overrode the score for submission sub-2.'
  },
  {
    id: 'log-4',
    performerId: 'user-5',
    actionType: 'task_update',
    timestamp: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    targetEntity: { type: 'Task', id: 'task-4', name: 'Fullstack Project Challenge' },
    status: 'Success',
    description: 'Ethan Employer created a new task "Fullstack Project Challenge".'
  },
  {
    id: 'log-5',
    performerId: 'user-4',
    actionType: 'login',
    timestamp: new Date(new Date().setHours(new Date().getHours() - 1)).toISOString(),
    targetEntity: { type: 'User', id: 'user-4', name: 'Diana Developer' },
    status: 'Success',
    description: 'Diana Developer logged in.'
  },
  {
    id: 'log-6',
    performerId: 'user-2',
    actionType: 'login',
    timestamp: new Date().toISOString(),
    targetEntity: { type: 'User', id: 'user-2', name: 'Bob Company' },
    status: 'Failed',
    description: 'Bob Company failed to log in (invalid password).'
  },
    {
    id: 'log-7',
    performerId: 'user-3',
    actionType: 'user_created',
    timestamp: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString(),
    targetEntity: { type: 'User', id: 'user-4', name: 'Diana Developer' },
    status: 'Success',
    description: 'Admin created a new candidate user: Diana Developer.'
  },
  {
    id: 'log-8',
    performerId: 'user-3',
    actionType: 'company_created',
    timestamp: new Date(new Date().setDate(new Date().getDate() - 20)).toISOString(),
    targetEntity: { type: 'Company', id: 'company-2', name: 'Innovate Inc.' },
    status: 'Success',
    description: 'Admin created a new company profile: Innovate Inc.'
  },
];
