import type { User, Company, Task, Submission, Evaluation, TaskTemplate } from './types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Alice Candidate',
    email: 'alice@example.com',
    role: 'candidate',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 30)).toISOString(),
    isActive: true,
    isVerified: true,
    profile: {
      avatarUrl: 'https://picsum.photos/seed/avatar1/100/100',
      bio: 'Aspiring frontend developer with a passion for React.',
      location: 'San Francisco, CA',
      experienceLevel: 'Intermediate',
      skills: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS'],
      githubUrl: 'https://github.com/alice-candidate',
      linkedinUrl: 'https://linkedin.com/in/alice-candidate',
    },
    candidatePerformance: {
      completedTasks: 2,
      averageScore: 92,
      ranking: 15,
    },
  },
  {
    id: 'user-2',
    name: 'Bob Company',
    email: 'bob@techcorp.com',
    role: 'company',
    companyId: 'company-1',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 60)).toISOString(),
    isActive: true,
    isVerified: true,
    profile: {
      avatarUrl: 'https://picsum.photos/seed/avatar2/100/100',
      bio: 'Hiring manager at TechCorp.',
    },
  },
  {
    id: 'user-3',
    name: 'Charlie Admin',
    email: 'charlie@skillmatch.pro',
    role: 'admin',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 120)).toISOString(),
    isActive: true,
    isVerified: true,
    profile: {
      avatarUrl: 'https://picsum.photos/seed/avatar3/100/100',
    },
  },
  {
    id: 'user-4',
    name: 'Diana Developer',
    email: 'diana@example.com',
    role: 'candidate',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString(),
    isActive: true,
    isVerified: true,
    profile: {
      avatarUrl: 'https://picsum.photos/seed/avatar4/100/100',
      bio: 'Full-stack engineer with 5 years of experience.',
      location: 'New York, NY',
      experienceLevel: 'Advanced',
      skills: ['Node.js', 'Python', 'GraphQL', 'AWS'],
      githubUrl: 'https://github.com/diana-dev',
    },
    candidatePerformance: {
      completedTasks: 1,
      averageScore: 88,
      ranking: 23,
    },
  },
  {
    id: 'user-5',
    name: 'Ethan Employer',
    email: 'ethan@innovate.io',
    role: 'company',
    companyId: 'company-2',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 20)).toISOString(),
    isActive: true,
    isVerified: true,
    profile: {
      avatarUrl: 'https://picsum.photos/seed/avatar5/100/100',
      bio: 'Lead Recruiter at Innovate Inc.',
    },
  },
];

export const mockCompanies: Company[] = [
  {
    id: 'company-1',
    name: 'TechCorp',
    description: 'A leading innovator in cloud solutions.',
    ownerId: 'user-2',
    website: 'https://techcorp.com',
    logoUrl: 'https://picsum.photos/seed/company1/100/100',
    industry: 'Technology',
    location: 'Silicon Valley, CA',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 60)).toISOString(),
    isActive: true,
    isVerified: true,
  },
  {
    id: 'company-2',
    name: 'Innovate Inc.',
    description: 'Building the future of decentralized applications.',
    ownerId: 'user-5',
    website: 'https://innovate.io',
    logoUrl: 'https://picsum.photos/seed/company2/100/100',
    industry: 'FinTech',
    location: 'New York, NY',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 20)).toISOString(),
    isActive: true,
    isVerified: false,
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Build a Responsive Navbar Component',
    description: 'The goal of this task is to create a reusable and responsive navigation bar for a modern web application.',
    instructions: '1. Use React and Tailwind CSS.\n2. The navbar should have a logo, navigation links, and a call-to-action button.\n3. It must collapse into a hamburger menu on mobile screens (under 768px).\n4. The state of the mobile menu (open/closed) should be managed within the component.',
    expectedOutputs: 'A single React component file (.tsx) containing the Navbar. The component should be self-contained and ready to be used in a Next.js project. No external state management libraries should be used.',
    roleCategory: 'Engineering',
    taskTypes: ['Coding', 'Design'],
    difficulty: 'Intermediate',
    deadline: '2024-08-15T23:59:59Z',
    timeLimitMinutes: 120,
    companyId: 'company-1',
    createdBy: 'user-2',
    status: 'published',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 9)).toISOString(),
    assignedCandidateIds: ['user-1'],
  },
  {
    id: 'task-2',
    title: 'Design a Database Schema for a Blog',
    description: 'This task requires you to design a normalized database schema for a typical blogging platform.',
    instructions: '1. Identify the core entities: Users, Posts, Comments, and Tags.\n2. Define the attributes for each entity.\n3. Establish the relationships between entities (e.g., one-to-many, many-to-many).\n4. Provide the schema as a SQL CREATE TABLE script.',
    expectedOutputs: 'A single .sql file containing the SQL statements to create all necessary tables, columns, primary keys, and foreign keys.',
    roleCategory: 'Data',
    taskTypes: ['Documentation'],
    difficulty: 'Beginner',
    deadline: '2024-08-20T23:59:59Z',
    companyId: 'company-1',
    createdBy: 'user-2',
    status: 'published',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
  },
  {
    id: 'task-3',
    title: 'Create a Serverless API Endpoint',
    description: 'Build a serverless function that acts as a proxy to a third-party API, adding caching to reduce latency.',
    instructions: '1. Choose a serverless provider (e.g., AWS Lambda, Vercel Functions).\n2. The function should accept a stock ticker symbol (e.g., "AAPL").\n3. It should fetch stock data from a free API like Alpha Vantage or Financial Modeling Prep.\n4. Cache the response for 5 minutes to avoid hitting API rate limits.\n5. Handle potential errors from the third-party API gracefully.',
    expectedOutputs: 'A link to a public GitHub repository containing your serverless function code and a brief README explaining how to deploy and test it.',
    roleCategory: 'Engineering',
    taskTypes: ['Coding'],
    difficulty: 'Advanced',
    deadline: '2024-08-25T23:59:59Z',
    companyId: 'company-2',
    createdBy: 'user-5',
    status: 'closed',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 15)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 14)).toISOString(),
  },
];

export const mockTemplates: TaskTemplate[] = [
  {
    templateId: 'TPL-ENG-001',
    title: 'Frontend Responsive Component',
    description: 'A standard task to create a reusable and responsive component for a modern web application.',
    instructions: '1. Use React and Tailwind CSS.\n2. Component should have standard elements like a header, content, and footer.\n3. It must be responsive across mobile, tablet, and desktop breakpoints.\n4. Manage state internally without external libraries.',
    expectedOutputs: 'A single React component file (.tsx) that is self-contained and ready for use.',
    roleCategory: 'Engineering',
    taskTypes: ['Coding', 'Design'],
    difficulty: 'Intermediate',
    timeLimitMinutes: 120,
    createdBy: 'company-1',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 40)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 40)).toISOString(),
  },
  {
    templateId: 'TPL-DATA-001',
    title: 'Blog Database Schema Design',
    description: 'This task requires designing a normalized database schema for a typical blogging platform.',
    instructions: '1. Identify the core entities: Users, Posts, Comments, and Tags.\n2. Define attributes for each entity.\n3. Establish relationships (one-to-many, many-to-many).\n4. Provide the schema as a SQL CREATE TABLE script.',
    expectedOutputs: 'A single .sql file with SQL statements for tables, columns, PKs, and FKs.',
    roleCategory: 'Data',
    taskTypes: ['Documentation'],
    difficulty: 'Beginner',
    timeLimitMinutes: 60,
    createdBy: 'company-1',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 35)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 35)).toISOString(),
  }
];

export const mockSubmissions: Submission[] = [
  {
    id: 'sub-1',
    taskId: 'task-1',
    userId: 'user-1',
    companyId: 'company-1',
    content: {
      type: 'link',
      value: 'https://github.com/alice-candidate/responsive-navbar',
    },
    status: 'evaluated',
    submittedAt: '2024-08-10T10:00:00Z',
  },
  {
    id: 'sub-2',
    taskId: 'task-1',
    userId: 'user-4',
    companyId: 'company-1',
    content: {
      type: 'link',
      value: 'https://github.com/diana-developer/navbar-project',
    },
    status: 'in-review',
    submittedAt: '2024-08-11T14:30:00Z',
  },
  {
    id: 'sub-3',
    taskId: 'task-2',
    userId: 'user-1',
    companyId: 'company-1',
    content: {
      type: 'link',
      value: 'https://gist.github.com/alice-candidate/schema.sql',
    },
    status: 'pending',
    submittedAt: '2024-08-12T09:00:00Z',
  },
];

export const mockEvaluations: Evaluation[] = [
  {
    id: 'eval-1',
    submissionId: 'sub-1',
    score: 92,
    feedback:
      'Excellent work! The component is well-structured and fully responsive. Great use of Tailwind CSS variants. Consider adding ARIA attributes for better accessibility.',
    evaluatedBy: 'user-2',
    evaluatedAt: '2024-08-11T18:00:00Z',
  },
];
