
import type { User, Company, Task, Submission, Evaluation, TaskTemplate, SubmissionContentType, EvaluationSchema, Activity, Notification, TestCase, GitHubRepository, Webhook, WebhookTriggerLog } from './types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Alice Candidate',
    email: 'alice@example.com',
    role: 'candidate',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 30)).toISOString(),
    isActive: true,
    isVerified: true,
    profile: {
      avatarUrl: 'https://picsum.photos/seed/avatar1/100/100',
      bio: 'Aspiring frontend developer with a passion for React.',
      location: 'San Francisco, CA',
      experienceLevel: 'Intermediate',
      skills: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS'],
      githubUrl: 'https://github.com/alice-candidate',
      linkedinUrl: 'https://linkedin.com/in/alice-candidate',
    },
    candidatePerformance: {
      completedTasks: 2,
      averageScore: 92,
      ranking: 15,
    },
  },
  {
    id: 'user-2',
    name: 'Bob Company',
    email: 'bob@techcorp.com',
    role: 'company',
    companyId: 'company-1',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 60)).toISOString(),
    isActive: true,
    isVerified: true,
    onboardingCompleted: true,
    profile: {
      avatarUrl: 'https://picsum.photos/seed/avatar2/100/100',
      bio: 'Hiring manager at TechCorp.',
    },
  },
  {
    id: 'user-3',
    name: 'Charlie Admin',
    email: 'charlie@skillmatch.pro',
    role: 'admin',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 120)).toISOString(),
    isActive: true,
    isVerified: true,
    profile: {
      avatarUrl: 'https://picsum.photos/seed/avatar3/100/100',
    },
  },
  {
    id: 'user-4',
    name: 'Diana Developer',
    email: 'diana@example.com',
    role: 'candidate',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString(),
    isActive: false, // Changed for testing
    isVerified: true,
    profile: {
      avatarUrl: 'https://picsum.photos/seed/avatar4/100/100',
      bio: 'Full-stack engineer with 5 years of experience.',
      location: 'New York, NY',
      experienceLevel: 'Advanced',
      skills: ['Node.js', 'Python', 'GraphQL', 'AWS'],
      githubUrl: 'https://github.com/diana-dev',
    },
    candidatePerformance: {
      completedTasks: 1,
      averageScore: 88,
      ranking: 23,
    },
  },
  {
    id: 'user-5',
    name: 'Ethan Employer',
    email: 'ethan@innovate.io',
    role: 'company',
    companyId: 'company-2',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 20)).toISOString(),
    isActive: true,
    isVerified: true,
    onboardingCompleted: true,
    profile: {
      avatarUrl: 'https://picsum.photos/seed/avatar5/100/100',
      bio: 'Lead Recruiter at Innovate Inc.',
    },
  },
];

export const mockCompanies: Company[] = [
  {
    id: 'company-1',
    name: 'TechCorp',
    description: 'A leading innovator in cloud solutions.',
    ownerId: 'user-2',
    website: 'https://techcorp.com',
    logoUrl: 'https://picsum.photos/seed/company1/100/100',
    industry: 'Technology',
    location: 'Silicon Valley, CA',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 60)).toISOString(),
    isActive: true,
    isVerified: true,
  },
  {
    id: 'company-2',
    name: 'Innovate Inc.',
    description: 'Building the future of decentralized applications.',
    ownerId: 'user-5',
    website: 'https://innovate.io',
    logoUrl: 'https://picsum.photos/seed/company2/100/100',
    industry: 'FinTech',
    location: 'New York, NY',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 20)).toISOString(),
    isActive: true,
    isVerified: false,
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Build a Responsive Navbar Component',
    description: 'The goal of this task is to create a reusable and responsive navigation bar for a modern web application.',
    instructions: '1. Use React and Tailwind CSS.\n2. The navbar should have a logo, navigation links, and a call-to-action button.\n3. It must collapse into a hamburger menu on mobile screens (under 768px).\n4. The state of the mobile menu (open/closed) should be managed within the component.',
    expectedOutputs: 'A single React component file (.tsx) containing the Navbar. The component should be self-contained and ready to be used in a Next.js project. No external state management libraries should be used.',
    roleCategory: 'Engineering',
    taskTypes: ['Coding', 'Design'],
    difficulty: 'Intermediate',
    priority: 'Medium',
    deadline: '2024-08-15T23:59:59Z',
    timeLimitMinutes: 120,
    companyId: 'company-1',
    createdBy: 'user-2',
    status: 'published',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 9)).toISOString(),
    multiRound: false,
  },
  {
    id: 'task-2',
    title: 'Design a Database Schema for a Blog',
    description: 'This task requires you to design a normalized database schema for a typical blogging platform.',
    instructions: '1. Identify the core entities: Users, Posts, Comments, and Tags.\n2. Define the attributes for each entity.\n3. Establish the relationships between entities (e.g., one-to-many, many-to-many).\n4. Provide the schema as a SQL CREATE TABLE script.',
    expectedOutputs: 'A single .sql file containing the SQL statements to create all necessary tables, columns, primary keys, and foreign keys.',
    roleCategory: 'Data',
    taskTypes: ['Documentation'],
    difficulty: 'Beginner',
    priority: 'Low',
    deadline: '2024-08-20T23:59:59Z',
    companyId: 'company-1',
    createdBy: 'user-2',
    status: 'published',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
    multiRound: false,
  },
  {
    id: 'task-3',
    title: 'Create a Serverless API Endpoint',
    description: 'Build a serverless function that acts as a proxy to a third-party API, adding caching to reduce latency.',
    instructions: '1. Choose a serverless provider (e.g., AWS Lambda, Vercel Functions).\n2. The function should accept a stock ticker symbol (e.g., "AAPL").\n3. It should fetch stock data from a free API like Alpha Vantage or Financial Modeling Prep.\n4. Cache the response for 5 minutes to avoid hitting API rate limits.\n5. Handle potential errors from the third-party API gracefully.',
    expectedOutputs: 'A link to a public GitHub repository containing your serverless function code and a brief README explaining how to deploy and test it.',
    roleCategory: 'Engineering',
    taskTypes: ['Coding'],
    difficulty: 'Advanced',
    priority: 'High',
    deadline: '2024-08-25T23:59:59Z',
    companyId: 'company-2',
    createdBy: 'user-5',
    status: 'closed',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 15)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 14)).toISOString(),
    multiRound: false,
  },
  {
    id: 'task-4',
    title: 'Fullstack Project Challenge',
    description: 'A comprehensive challenge involving both frontend and backend development to build a mini-application.',
    instructions: '', // Empty for multi-round
    expectedOutputs: '', // Empty for multi-round
    roleCategory: 'Engineering',
    taskTypes: ['Coding', 'Project', 'Documentation'],
    difficulty: 'Expert',
    priority: 'High',
    deadline: '2024-09-30T23:59:59Z',
    companyId: 'company-2',
    createdBy: 'user-5',
    status: 'published',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    multiRound: true,
    rounds: [
      {
        roundNumber: 1,
        instructions: 'Design and build the backend API. It should have endpoints for creating and retrieving user data. Use Node.js and Express.',
        expectedOutputs: 'A set of functional REST API endpoints deployed on a test server.',
        timeLimitMinutes: 180,
      },
      {
        roundNumber: 2,
        instructions: 'Build the frontend interface that consumes the API from Round 1. It should have a form to create a user and a table to display users.',
        expectedOutputs: 'A responsive single-page application built with React.',
        timeLimitMinutes: 240,
      },
    ],
  },
  {
    id: 'task-5',
    title: 'Implement a Draggable Kanban Board UI',
    description: 'Create a fully functional Kanban board UI where users can drag and drop tasks between columns.',
    instructions: '1. Use React and a library like `react-beautiful-dnd` or `dnd-kit`.\n2. Create three columns: "To Do", "In Progress", "Done".\n3. Tasks should be represented as cards.\n4. The state of the board should be managed within the React component.',
    expectedOutputs: 'A single React component file (.tsx) demonstrating the draggable Kanban board.',
    roleCategory: 'Engineering',
    taskTypes: ['UI', 'Component', 'Feature Implementation'],
    difficulty: 'Advanced',
    priority: 'High',
    deadline: new Date(new Date().setDate(new Date().getDate() + 14)).toISOString(),
    companyId: 'company-1',
    createdBy: 'user-2',
    status: 'published',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
    multiRound: false,
    imageUrl: 'https://picsum.photos/seed/kanban/600/400',
    imageHint: 'kanban board'
  },
  {
    id: 'task-6',
    title: 'Style a Login Form with Tailwind CSS',
    description: 'Given a basic HTML structure for a login form, apply styling using Tailwind CSS to make it visually appealing and responsive.',
    instructions: '1. Use the provided HTML markup.\n2. Apply Tailwind CSS classes to style all form elements.\n3. Ensure the form is centered on the page and looks good on both desktop and mobile devices.',
    expectedOutputs: 'An HTML file with inline Tailwind CSS classes applied.',
    roleCategory: 'Engineering',
    taskTypes: ['Styling', 'UI'],
    difficulty: 'Beginner',
    priority: 'Low',
    deadline: new Date(new Date().setDate(new Date().getDate() + 7)).toISOString(),
    companyId: 'company-2',
    createdBy: 'user-5',
    status: 'published',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
    multiRound: false,
  },
  {
    id: 'task-7',
    title: 'Create a Reusable Button Component',
    description: 'Develop a flexible and reusable Button component in React that supports different variants, sizes, and states.',
    instructions: '1. The component should accept `variant` (primary, secondary, destructive), `size` (sm, md, lg), and `disabled` props.\n2. Use a library like `class-variance-authority` to manage styles.\n3. The component should render a `<button>` element and forward any other props to it.',
    expectedOutputs: 'A single React component file (.tsx) for the Button.',
    roleCategory: 'Engineering',
    taskTypes: ['Component'],
    difficulty: 'Intermediate',
    priority: 'Medium',
    deadline: new Date(new Date().setDate(new Date().getDate() + 21)).toISOString(),
    companyId: 'company-1',
    createdBy: 'user-2',
    status: 'published',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 4)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 4)).toISOString(),
    multiRound: false,
  },
  {
    id: 'task-8',
    title: 'Implement Dark Mode Toggle Feature',
    description: 'Add a dark mode toggle to a simple application. The user\'s preference should be saved in localStorage.',
    instructions: '1. Add a button to toggle between light and dark themes.\n2. Use CSS variables to manage colors for both themes.\n3. When the theme changes, add a `.dark` class to the `<html>` element.\n4. Persist the selected theme in `localStorage`.',
    expectedOutputs: 'A link to a GitHub repository with the complete project.',
    roleCategory: 'Engineering',
    taskTypes: ['Feature Implementation', 'Styling'],
    difficulty: 'Intermediate',
    priority: 'Medium',
    deadline: new Date(new Date().setDate(new Date().getDate() + 10)).toISOString(),
    companyId: 'company-2',
    createdBy: 'user-5',
    status: 'published',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
    multiRound: false,
  },
  {
    id: 'task-9',
    title: 'Refactor a Class Component to a Functional Component',
    description: 'Take an existing React class component and refactor it into a modern functional component using hooks.',
    instructions: '1. Convert all lifecycle methods (e.g., `componentDidMount`) to their `useEffect` equivalents.\n2. Convert the component\'s state management from `this.setState` to the `useState` hook.',
    expectedOutputs: 'The refactored functional component file (.tsx).',
    roleCategory: 'Engineering',
    taskTypes: ['Coding'],
    difficulty: 'Beginner',
    priority: 'Low',
    deadline: new Date(new Date().setDate(new Date().getDate() + 5)).toISOString(),
    companyId: 'company-1',
    createdBy: 'user-2',
    status: 'draft', // Example of a non-published task
    createdAt: new Date(new Date().setDate(new Date().getDate() - 6)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 6)).toISOString(),
    multiRound: false,
  },
  {
    id: 'task-10',
    title: 'Design a Landing Page Mockup',
    description: 'Create a high-fidelity mockup for a new SaaS product landing page.',
    instructions: '1. Design a hero section, a features section, and a pricing section.\n2. The design should be modern, clean, and professional.\n3. You can use any design tool you prefer (e.g., Figma, Sketch, Adobe XD).',
    expectedOutputs: 'A shareable link to your design file or a high-resolution image of the mockup.',
    roleCategory: 'Design',
    taskTypes: ['Design', 'UI'],
    difficulty: 'Intermediate',
    deadline: new Date(new Date().setDate(new Date().getDate() + 8)).toISOString(),
    companyId: 'company-2',
    createdBy: 'user-5',
    status: 'published',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    imageUrl: 'https://picsum.photos/seed/landingpage/600/400',
    imageHint: 'website design',
    multiRound: false,
  },
  {
    id: 'task-11',
    title: 'Develop a Content Strategy for a Product Launch',
    description: 'Create a one-month content calendar for the launch of a new productivity app.',
    instructions: '1. Define 3 key content themes.\n2. Outline 4 blog post ideas (titles and brief descriptions).\n3. Propose 8 social media posts (for LinkedIn and Twitter).\n4. Create one concept for a launch-day newsletter.',
    expectedOutputs: 'A PDF or Google Doc containing the content strategy and calendar.',
    roleCategory: 'Marketing',
    taskTypes: ['Campaign Planning', 'Content Creation', 'Social Media'],
    difficulty: 'Intermediate',
    deadline: new Date(new Date().setDate(new Date().getDate() + 12)).toISOString(),
    companyId: 'company-1',
    createdBy: 'user-2',
    status: 'published',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 7)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 7)).toISOString(),
    multiRound: false,
  },
  {
    id: 'task-12',
    title: 'Write an SEO-Optimized Blog Post',
    description: 'Write a 1000-word blog post on the topic "The Future of Remote Collaboration Tools".',
    instructions: '1. Target the primary keyword "remote collaboration tools".\n2. Include at least two secondary keywords like "virtual teamwork" and "hybrid work".\n3. Structure the post with clear headings (H2, H3).\n4. Include an introduction, a conclusion, and at least 3 internal links (to mock URLs).',
    expectedOutputs: 'A Google Doc or Word document with the final blog post.',
    roleCategory: 'Marketing',
    taskTypes: ['Content Creation'],
    difficulty: 'Beginner',
    deadline: new Date(new Date().setDate(new Date().getDate() + 6)).toISOString(),
    companyId: 'company-2',
    createdBy: 'user-5',
    status: 'published',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 8)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 8)).toISOString(),
    multiRound: false,
  },
  {
    id: 'task-13',
    title: 'Plan a Social Media Campaign for a Holiday Sale',
    description: 'Plan a 3-day social media campaign for a Black Friday sale.',
    instructions: '1. Define the target audience.\n2. Create 3 distinct ad copy variations (headline and body) for Facebook/Instagram.\n3. Mock up one visual concept for the ads (a simple description or a link to a Canva/Figma design is fine).\n4. Outline the campaign schedule (pre-launch, launch day, final hours).',
    expectedOutputs: 'A presentation (PPT, Google Slides) outlining the campaign plan.',
    roleCategory: 'Marketing',
    taskTypes: ['Campaign Planning', 'Ads', 'Social Media'],
    difficulty: 'Intermediate',
    deadline: new Date(new Date().setDate(new Date().getDate() + 9)).toISOString(),
    companyId: 'company-1',
    createdBy: 'user-2',
    status: 'published',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 9)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 9)).toISOString(),
    multiRound: false,
  },
  {
    id: 'task-14',
    title: 'Go-to-Market Strategy Presentation',
    description: 'Develop a 10-slide presentation outlining the go-to-market strategy for a new B2B SaaS product targeting small businesses.',
    instructions: '1. Define the Ideal Customer Profile (ICP).\n2. Outline the pricing strategy.\n3. Detail the marketing and sales channels.\n4. Set key performance indicators (KPIs) for the first six months.',
    expectedOutputs: 'A PDF or PPTX file of the presentation.',
    roleCategory: 'Business',
    taskTypes: ['Strategy Planning', 'Presentation', 'Market Analysis'],
    difficulty: 'Advanced',
    priority: 'High',
    deadline: new Date(new Date().setDate(new Date().getDate() + 15)).toISOString(),
    companyId: 'company-1',
    createdBy: 'user-2',
    status: 'published',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
    multiRound: false,
    imageUrl: 'https://picsum.photos/seed/business/600/400',
    imageHint: 'business strategy'
  },
  {
    id: 'task-15',
    title: 'Financial Model for New Product Line',
    description: 'Create a 3-year financial projection for a new product line. The model should include revenue forecasts, cost of goods sold (COGS), and operational expenses.',
    instructions: '1. Use the provided assumptions for market size and growth rate.\n2. Create a P&L statement forecast.\n3. Calculate the break-even point.\n4. The model should be clear, well-structured, and easy to understand.',
    expectedOutputs: 'An Excel file (.xlsx) or Google Sheets link containing the financial model.',
    roleCategory: 'Business',
    taskTypes: ['Financial Modeling'],
    difficulty: 'Expert',
    priority: 'Medium',
    deadline: new Date(new Date().setDate(new Date().getDate() + 20)).toISOString(),
    companyId: 'company-2',
    createdBy: 'user-5',
    status: 'published',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    multiRound: false,
  },
  {
    id: 'task-16',
    title: 'Analyze Sales Data and Create Dashboard',
    description: 'Analyze a provided sales dataset to identify trends and create a visualization dashboard.',
    instructions: '1. Clean the provided CSV data.\n2. Analyze monthly revenue and top-selling products.\n3. Create a dashboard with at least 3 charts (e.g., bar, line, pie) to visualize your findings.\n4. Provide a summary of your key insights.',
    expectedOutputs: 'A link to a public dashboard (e.g., Tableau, Power BI, Looker) or a Jupyter Notebook containing your analysis and visualizations.',
    roleCategory: 'Data',
    taskTypes: ['Data Cleaning', 'Visualization', 'Reporting'],
    difficulty: 'Intermediate',
    priority: 'Medium',
    deadline: new Date(new Date().setDate(new Date().getDate() + 14)).toISOString(),
    companyId: 'company-1',
    createdBy: 'user-2',
    status: 'published',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
    multiRound: false,
    imageUrl: 'https://picsum.photos/seed/dataviz/600/400',
    imageHint: 'data dashboard'
  }
];

export const mockTemplates: TaskTemplate[] = [
  {
    templateId: 'TPL-ENG-001',
    title: 'Frontend Responsive Component',
    description: 'A standard task to create a reusable and responsive component for a modern web application.',
    instructions: '1. Use React and Tailwind CSS.\n2. Component should have standard elements like a header, content, and footer.\n3. It must be responsive across mobile, tablet, and desktop breakpoints.\n4. Manage state internally without external libraries.',
    expectedOutputs: 'A single React component file (.tsx) that is self-contained and ready for use.',
    roleCategory: 'Engineering',
    taskTypes: ['Coding', 'Design'],
    difficulty: 'Intermediate',
    timeLimitMinutes: 120,
    createdBy: 'company-1',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 40)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 40)).toISOString(),
    multiRound: false,
  },
  {
    templateId: 'TPL-DATA-001',
    title: 'Blog Database Schema Design',
    description: 'This task requires designing a normalized database schema for a typical blogging platform.',
    instructions: '1. Identify the core entities: Users, Posts, Comments, and Tags.\n2. Define attributes for each entity.\n3. Establish relationships (one-to-many, many-to-many).\n4. Provide the schema as a SQL CREATE TABLE script.',
    expectedOutputs: 'A single .sql file with SQL statements for tables, columns, PKs, and FKs.',
    roleCategory: 'Data',
    taskTypes: ['Documentation'],
    difficulty: 'Beginner',
    timeLimitMinutes: 60,
    createdBy: 'company-1',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 35)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 35)).toISOString(),
    multiRound: false,
  },
  {
    templateId: 'TPL-ENG-002',
    title: 'Fullstack Mini-App (2 Rounds)',
    description: 'A comprehensive challenge involving both frontend and backend development to build a mini-application.',
    instructions: '',
    expectedOutputs: '',
    roleCategory: 'Engineering',
    taskTypes: ['Coding', 'Project'],
    difficulty: 'Expert',
    createdBy: 'company-2',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 30)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 30)).toISOString(),
    multiRound: true,
    rounds: [
      { roundNumber: 1, instructions: 'Build the REST API for CRUD operations on a "notes" resource.', expectedOutputs: 'A GitHub repo with the backend code and a Postman collection.', timeLimitMinutes: 120 },
      { roundNumber: 2, instructions: 'Build a React frontend to consume the "notes" API.', expectedOutputs: 'A deployed frontend application link.', timeLimitMinutes: 180 },
    ],
  }
];

export const mockSubmissions: Submission[] = [
  {
    id: 'sub-1',
    taskId: 'task-1',
    userId: 'user-1',
    companyId: 'company-1',
    content: {
      type: 'link',
      value: 'https://github.com/alice-candidate/responsive-navbar',
    },
    status: 'shortlisted',
    validationStatus: 'Valid',
    testCaseStatus: 'Passed',
    autoScoringStatus: 'Completed',
    autoScore: 88,
    sandboxStatus: 'Completed',
    liveSessionStatus: 'Completed',
    plagiarismRisk: 'Low',
    recordingStatus: 'Completed',
    assignedAt: '2024-08-09T10:00:00Z',
    submittedAt: '2024-08-10T10:00:00Z',
    lastUpdated: '2024-08-12T09:00:00Z',
    timeSpentMinutes: 115,
  },
  {
    id: 'sub-2',
    taskId: 'task-1',
    userId: 'user-4',
    companyId: 'company-1',
    content: {
      type: 'link',
      value: 'https://github.com/diana-developer/navbar-project',
    },
    status: 'rejected',
    validationStatus: 'Invalid',
    testCaseStatus: 'Failed',
    autoScoringStatus: 'Completed',
    autoScore: 62,
    sandboxStatus: 'Completed',
    liveSessionStatus: 'Not Started',
    plagiarismRisk: 'High',
    recordingStatus: 'Completed',
    assignedAt: '2024-08-10T11:00:00Z',
    submittedAt: '2024-08-11T14:30:00Z',
    lastUpdated: '2024-08-12T11:00:00Z',
    timeSpentMinutes: 130,
  },
  {
    id: 'sub-3',
    taskId: 'task-2',
    userId: 'user-1',
    companyId: 'company-1',
    status: 'resubmitted',
    validationStatus: 'Warning',
    testCaseStatus: 'Warning',
    autoScoringStatus: 'Pending',
    sandboxStatus: 'Idle',
    liveSessionStatus: 'Scheduled',
    plagiarismRisk: 'Low',
    recordingStatus: 'Recording',
    assignedAt: '2024-08-11T09:00:00Z',
    submittedAt: '2024-08-12T09:00:00Z',
    resubmittedAt: '2024-08-13T11:00:00Z',
    lastUpdated: '2024-08-13T11:00:00Z',
    content: {
        type: 'file',
        value: '/mock-uploads/alice-schema.sql',
        fileName: 'alice-schema-v2.sql',
    },
  },
  {
    id: 'sub-4',
    taskId: 'task-4',
    userId: 'user-1',
    companyId: 'company-2',
    status: 'in-progress',
    validationStatus: 'Pending',
    testCaseStatus: 'Pending',
    autoScoringStatus: 'Pending',
    sandboxStatus: 'Active',
    liveSessionStatus: 'Active',
    plagiarismRisk: 'None',
    recordingStatus: 'Recording',
    assignedAt: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
    lastUpdated: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
    currentRound: 1,
    attemptsCount: 1,
  },
   {
    id: 'sub-5',
    taskId: 'task-3',
    userId: 'user-1',
    companyId: 'company-2',
    status: 'assigned',
    validationStatus: 'Pending',
    testCaseStatus: 'Pending',
    autoScoringStatus: 'Pending',
    sandboxStatus: 'Not Started',
    liveSessionStatus: 'Cancelled',
    plagiarismRisk: 'None',
    recordingStatus: 'Not Started',
    assignedAt: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    lastUpdated: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    attemptsCount: 0,
  },
  {
    id: 'sub-6',
    taskId: 'task-2',
    userId: 'user-4',
    companyId: 'company-1',
    content: {
      type: 'file',
      value: '/mock-uploads/diana-schema.sql',
      fileName: 'diana-schema.sql',
      fileSize: 1536, // 1.5 KB
    },
    status: 'pending',
    validationStatus: 'Valid',
    testCaseStatus: 'Passed',
    autoScoringStatus: 'Completed',
    autoScore: 78,
    sandboxStatus: 'Error',
    liveSessionStatus: 'Not Started',
    plagiarismRisk: 'Medium',
    recordingStatus: 'Completed',
    assignedAt: new Date(new Date().setDate(new Date().getDate() - 4)).toISOString(),
    submittedAt: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
    lastUpdated: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
    timeSpentMinutes: 50,
  },
  {
    id: 'sub-7',
    taskId: 'task-10',
    userId: 'user-1',
    companyId: 'company-2',
    content: {
      type: 'externalLink',
      value: 'https://www.figma.com/proto/your-prototype-link',
    },
    status: 'evaluated',
    validationStatus: 'Warning',
    testCaseStatus: 'Warning',
    autoScoringStatus: 'Completed',
    autoScore: 91,
    sandboxStatus: 'Completed',
    liveSessionStatus: 'Completed',
    plagiarismRisk: 'Low',
    recordingStatus: 'Paused',
    assignedAt: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
    submittedAt: new Date(new Date().setDate(new Date().getDate() - 4)).toISOString(),
    lastUpdated: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
  },
];

export const mockEvaluations: Evaluation[] = [
  {
    id: 'eval-1',
    submissionId: 'sub-1',
    score: 84,
    criteriaScores: {
      'Proficiency': 9,
      'Best Practices': 8,
      'Clarity': 9,
      'Documentation': 7,
      'Analysis': 8,
      'Solution Quality': 9,
      'Innovation': 8,
      'Polish & Initiative': 9,
      'Collaboration': 8,
      'Proactiveness': 9,
    },
    criteriaComments: {
        'Proficiency': 'Great command of React hooks and state management.',
        'Best Practices': 'Code is clean and follows conventions. Could add more tests.',
        'Clarity': 'The video explanation was clear and concise.',
        'Documentation': 'The README was good, but could be more detailed.',
        'Analysis': 'Good breakdown of the problem.',
        'Solution Quality': 'The solution is robust and handles edge cases.',
        'Innovation': 'Nice use of a custom hook to abstract logic.',
        'Polish & Initiative': 'The UI is polished and looks great.',
        'Collaboration': 'Seems like they would be a great team player.',
        'Proactiveness': 'Showed initiative by adding a dark mode toggle.',
    },
    feedback:
      'Excellent work! The component is well-structured and fully responsive. Great use of Tailwind CSS variants. Consider adding ARIA attributes for better accessibility.',
    evaluatedBy: 'user-2',
    evaluatedAt: '2024-08-11T18:00:00Z',
  },
  {
    id: 'eval-2',
    submissionId: 'sub-3',
    score: 75,
    criteriaScores: {
        'Proficiency': 7,
        'Best Practices': 8,
        'Clarity': 9,
        'Documentation': 6,
        'Analysis': 9,
        'Solution Quality': 7,
        'Innovation': 6,
        'Polish & Initiative': 7,
        'Collaboration': 8,
        'Proactiveness': 8,
    },
    criteriaComments: {
        'Proficiency': 'Good understanding of SQL basics.',
        'Best Practices': 'The schema is normalized, which is good.',
        'Clarity': 'The explanation was easy to follow.',
        'Documentation': 'Could use more comments in the SQL file.',
        'Analysis': 'Correctly identified the main entities.',
        'Solution Quality': 'The main issue was the many-to-many relationship handling.',
        'Innovation': 'Standard approach, which is fine for this task.',
        'Polish & Initiative': 'The submission was clean and to the point.',
        'Collaboration': 'N/A',
        'Proactiveness': 'N/A',
    },
    feedback:
      'The SQL script is mostly correct, but the relationship between Posts and Tags should be many-to-many, requiring a join table. The schema is otherwise well-defined.',
    evaluatedBy: 'user-2',
    evaluatedAt: '2024-08-12T15:00:00Z',
  },
  {
    id: 'eval-3',
    submissionId: 'sub-2',
    score: 65,
    criteriaScores: {
      'Proficiency': 7,
      'Best Practices': 6,
      'Clarity': 8,
      'Documentation': 5,
      'Analysis': 7,
      'Solution Quality': 6,
      'Innovation': 5,
      'Polish & Initiative': 7,
      'Collaboration': 8,
      'Proactiveness': 6,
    },
    criteriaComments: {},
    feedback:
      'The submission was okay, but did not meet all requirements. The mobile view was not fully responsive.',
    evaluatedBy: 'user-2',
    evaluatedAt: '2024-08-12T10:00:00Z',
  },
    {
    id: 'eval-4',
    submissionId: 'sub-7',
    score: 92,
    criteriaScores: {
      'Proficiency': 9,
      'Best Practices': 9,
      'Clarity': 10,
      'Documentation': 8,
      'Analysis': 9,
      'Solution Quality': 9,
      'Innovation': 9,
      'Polish & Initiative': 10,
      'Collaboration': 9,
      'Proactiveness': 9,
    },
    feedback: 'Outstanding design work. The mockup is pixel-perfect and the user flow is intuitive and well-thought-out.',
    evaluatedBy: 'user-5',
    evaluatedAt: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
  },
];

export const mockTestCases: (TestCase & { submissionId: string })[] = [
    {
        submissionId: 'sub-1',
        id: 'tc-1-1',
        name: 'GET /api/items Endpoint',
        description: 'Checks if the endpoint returns a 200 OK status.',
        expectedOutcome: 'Status 200 with a JSON array of items.',
        actualOutcome: 'Status 200 with a JSON array of items.',
        status: 'Passed'
    },
    {
        submissionId: 'sub-1',
        id: 'tc-1-2',
        name: 'POST /api/items Endpoint',
        description: 'Checks if a new item can be created successfully.',
        expectedOutcome: 'Status 201 Created with the new item in the response body.',
        actualOutcome: 'Status 201 Created with the new item in the response body.',
        status: 'Passed'
    },
    {
        submissionId: 'sub-1',
        id: 'tc-1-3',
        name: 'Authentication Middleware',
        description: 'Ensures that protected endpoints return 401 Unauthorized for unauthenticated requests.',
        expectedOutcome: 'Status 401 Unauthorized.',
        actualOutcome: 'Status 401 Unauthorized.',
        status: 'Passed'
    },
    {
        submissionId: 'sub-2',
        id: 'tc-2-1',
        name: 'GET /api/items/{id} Endpoint',
        description: 'Checks if a specific item can be retrieved.',
        expectedOutcome: 'Status 200 with the correct item.',
        actualOutcome: 'Status 200 with the correct item.',
        status: 'Passed'
    },
    {
        submissionId: 'sub-2',
        id: 'tc-2-2',
        name: 'GET /api/items/not-found',
        description: 'Checks for correct 404 handling for a non-existent item.',
        expectedOutcome: 'Status 404 Not Found.',
        actualOutcome: 'Status 500 Internal Server Error.',
        status: 'Failed'
    },
     {
        submissionId: 'sub-3',
        id: 'tc-3-1',
        name: 'Database Connection',
        description: 'Checks if the application successfully connects to the database on startup.',
        expectedOutcome: 'Successful database connection log.',
        actualOutcome: 'Connection timed out after 3 retries.',
        status: 'Failed'
    },
    {
        submissionId: 'sub-3',
        id: 'tc-3-2',
        name: 'Data Validation: Email Field',
        description: 'Checks if the API correctly validates email formats on user creation.',
        expectedOutcome: 'Status 400 Bad Request for invalid email format.',
        actualOutcome: 'Status 400 Bad Request for invalid email format.',
        status: 'Passed'
    },
];

export const mockEvaluationSchemas: EvaluationSchema[] = [
    {
        id: 'schema-1',
        name: 'Standard Technical Evaluation',
        description: 'A balanced schema for evaluating core technical roles.',
        isActive: true,
        criteria: [
            { id: 'crit-1-1', name: 'Technical Skills', description: 'Assesses mastery of required technologies and tools.', maxPoints: 10, weight: 0.3 },
            { id: 'crit-1-2', name: 'Problem Solving', description: 'Evaluates the ability to analyze problems and devise effective solutions.', maxPoints: 10, weight: 0.3 },
            { id: 'crit-1-3', name: 'Code Quality', description: 'Reviews code for readability, structure, and best practices.', maxPoints: 10, weight: 0.2 },
            { id: 'crit-1-4', name: 'Communication', description: 'Judges the clarity of explanations and thought process.', maxPoints: 10, weight: 0.2 },
        ],
    },
    {
        id: 'schema-2',
        name: 'Frontend Specialist Evaluation',
        description: 'A schema focused on frontend-specific skills and user experience.',
        isActive: false,
        criteria: [
            { id: 'crit-2-1', name: 'React Proficiency', description: 'Correct use of hooks, components, and state management.', maxPoints: 10, weight: 0.4 },
            { id: 'crit-2-2', name: 'UI/UX Implementation', description: 'Attention to detail in implementing the design.', maxPoints: 10, weight: 0.3 },
            { id: 'crit-2-3', name: 'Responsiveness', description: 'How well the solution adapts to different screen sizes.', maxPoints: 10, weight: 0.2 },
            { id: 'crit-2-4', name: 'Performance', description: 'Efficiency of the code and awareness of rendering performance.', maxPoints: 10, weight: 0.1 },
        ],
    },
    {
        id: 'schema-3',
        name: 'Soft Skills Assessment',
        description: 'Focuses on non-technical aspects like communication and teamwork.',
        isActive: true,
        criteria: [
            { id: 'crit-3-1', name: 'Clarity of Communication', description: 'How clearly ideas are presented.', maxPoints: 10, weight: 0.5 },
            { id: 'crit-3-2', name: 'Proactiveness', description: 'Did the candidate ask clarifying questions or suggest improvements?', maxPoints: 10, weight: 0.3 },
            { id: 'crit-3-3', name: 'Presentation', description: 'The overall quality and polish of the submission.', maxPoints: 10, weight: 0.2 },
        ],
    },
];

export const mockActivityLogs: Activity[] = [
  {
    id: 'log-1',
    performerId: 'user-1',
    actionType: 'submission',
    timestamp: '2024-08-10T10:00:00Z',
    targetEntity: { type: 'Submission', id: 'sub-1', name: 'Responsive Navbar' },
    status: 'Success',
    description: 'Alice Candidate submitted work for "Build a Responsive Navbar Component".'
  },
  {
    id: 'log-2',
    performerId: 'user-2',
    actionType: 'status_change',
    timestamp: '2024-08-12T09:00:00Z',
    targetEntity: { type: 'Submission', id: 'sub-1', name: 'Responsive Navbar' },
    status: 'Success',
    description: 'Bob Company changed status to Shortlisted for submission sub-1.'
  },
  {
    id: 'log-3',
    performerId: 'user-3',
    actionType: 'override',
    timestamp: new Date(new Date().setHours(new Date().getHours() - 2)).toISOString(),
    targetEntity: { type: 'Submission', id: 'sub-2', name: 'Navbar Project' },
    status: 'Success',
    description: 'Charlie Admin overrode the score for submission sub-2.'
  },
  {
    id: 'log-4',
    performerId: 'user-5',
    actionType: 'task_update',
    timestamp: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    targetEntity: { type: 'Task', id: 'task-4', name: 'Fullstack Project Challenge' },
    status: 'Success',
    description: 'Ethan Employer created a new task "Fullstack Project Challenge".'
  },
  {
    id: 'log-5',
    performerId: 'user-4',
    actionType: 'login',
    timestamp: new Date(new Date().setHours(new Date().getHours() - 1)).toISOString(),
    targetEntity: { type: 'User', id: 'user-4', name: 'Diana Developer' },
    status: 'Success',
    description: 'Diana Developer logged in.'
  },
  {
    id: 'log-6',
    performerId: 'user-2',
    actionType: 'login',
    timestamp: new Date().toISOString(),
    targetEntity: { type: 'User', id: 'user-2', name: 'Bob Company' },
    status: 'Failed',
    description: 'Bob Company failed to log in (invalid password).'
  },
    {
    id: 'log-7',
    performerId: 'user-3',
    actionType: 'user_created',
    timestamp: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString(),
    targetEntity: { type: 'User', id: 'user-4', name: 'Diana Developer' },
    status: 'Success',
    description: 'Admin created a new candidate user: Diana Developer.'
  },
  {
    id: 'log-8',
    performerId: 'user-3',
    actionType: 'company_created',
    timestamp: new Date(new Date().setDate(new Date().getDate() - 20)).toISOString(),
    targetEntity: { type: 'Company', id: 'company-2', name: 'Innovate Inc.' },
    status: 'Success',
    description: 'Admin created a new company profile: Innovate Inc.'
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'alert-1',
    type: 'task_deadline',
    priority: 'High',
    status: 'Unread',
    timestamp: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString(),
    title: 'Task Deadline Approaching',
    description: 'Task "Build a Responsive Navbar Component" is due in less than 24 hours.',
    relatedEntity: { type: 'Task', id: 'task-1', name: 'Build a Responsive Navbar Component' },
  },
  {
    id: 'alert-2',
    type: 'new_submission',
    priority: 'Medium',
    status: 'Unread',
    timestamp: new Date(new Date().setHours(new Date().getHours() - 1)).toISOString(),
    title: 'New Submission Received',
    description: 'A new submission was received from Diana Developer for "Database Schema Design".',
    relatedEntity: { type: 'Submission', id: 'sub-6' },
  },
  {
    id: 'alert-3',
    type: 'user_signup',
    priority: 'Low',
    status: 'Read',
    timestamp: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
    title: 'New Company Signed Up',
    description: 'A new company, "Innovate Inc.", has joined the platform.',
    relatedEntity: { type: 'Company', id: 'company-2', name: 'Innovate Inc.' },
  },
  {
    id: 'alert-4',
    type: 'system_warning',
    priority: 'High',
    status: 'Resolved',
    timestamp: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    title: 'High API Error Rate',
    description: 'Third-party API for stock data is reporting a high error rate (over 5%).',
    relatedEntity: { type: 'System', id: 'api-financial-prep', name: 'Financial Modeling Prep API' },
  },
  {
    id: 'alert-5',
    type: 'flagged_submission',
    priority: 'High',
    status: 'Unread',
    timestamp: new Date(new Date().setHours(new Date().getHours() - 3)).toISOString(),
    title: 'Submission Flagged for Review',
    description: 'Submission from a candidate was flagged for potential plagiarism.',
    relatedEntity: { type: 'Submission', id: 'sub-2', name: 'Navbar Project by Diana Developer' },
  },
  {
    id: 'alert-6',
    type: 'task_deadline',
    priority: 'Medium',
    status: 'Read',
    timestamp: new Date(new Date().setDate(new Date().getDate() + 3)).toISOString(),
    title: 'Task Deadline Approaching',
    description: 'Task "Create a Serverless API Endpoint" is due in 3 days.',
    relatedEntity: { type: 'Task', id: 'task-3', name: 'Create a Serverless API Endpoint' },
  },
];

export const mockGitHubRepositories: GitHubRepository[] = [
  {
    id: 'repo-1',
    name: 'alice-candidate/responsive-navbar',
    url: 'https://github.com/alice-candidate/responsive-navbar',
    ownerName: 'Alice Candidate',
    ownerId: 'user-1',
    status: 'Connected',
    lastSync: new Date(new Date().setHours(new Date().getHours() - 1)).toISOString(),
    commitCount: 15,
    branchCount: 3,
    lastCommitMessage: 'feat: add dark mode support',
  },
  {
    id: 'repo-2',
    name: 'diana-developer/navbar-project',
    url: 'https://github.com/diana-developer/navbar-project',
    ownerName: 'Diana Developer',
    ownerId: 'user-4',
    status: 'Error',
    lastSync: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    commitCount: 8,
    branchCount: 2,
    lastCommitMessage: 'fix: resolve mobile layout bug',
  },
  {
    id: 'repo-3',
    name: 'shared-team/fullstack-challenge',
    url: 'https://github.com/shared-team/fullstack-challenge',
    ownerName: 'TechCorp Team',
    ownerId: 'company-1',
    status: 'Connected',
    lastSync: new Date().toISOString(),
    commitCount: 42,
    branchCount: 5,
    lastCommitMessage: 'refactor: update database schema',
  },
    {
    id: 'repo-4',
    name: 'innovate-inc/marketing-site',
    url: 'https://github.com/innovate-inc/marketing-site',
    ownerName: 'Innovate Inc.',
    ownerId: 'company-2',
    status: 'Pending',
    lastSync: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
    commitCount: 3,
    branchCount: 1,
    lastCommitMessage: 'Initial commit',
  },
];

export const mockWebhooks: Webhook[] = [
  {
    id: 'wh-1',
    name: 'Zapier: New Submission',
    url: 'https://hooks.zapier.com/hooks/catch/12345/abcde/',
    events: ['submission.created'],
    status: 'Active',
    lastTriggered: new Date(new Date().setHours(new Date().getHours() - 2)).toISOString(),
  },
  {
    id: 'wh-2',
    name: 'Slack: Evaluation Completed',
    url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX',
    events: ['submission.evaluated'],
    status: 'Active',
    lastTriggered: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
  },
  {
    id: 'wh-3',
    name: 'Internal Analytics Service',
    url: 'https://internal-analytics.skillmatch.pro/webhook',
    events: ['submission.created', 'submission.evaluated', 'user.created'],
    status: 'Inactive',
  },
  {
    id: 'wh-4',
    name: 'External CRM Sync',
    url: 'https://crm.example.com/api/v1/webhook',
    events: ['user.created'],
    status: 'Error',
    lastTriggered: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
  },
];

export const mockWebhookTriggerLogs: WebhookTriggerLog[] = [
    { id: 'log-wh-1', webhookId: 'wh-1', timestamp: new Date(new Date().setHours(new Date().getHours() - 2)).toISOString(), status: 'Success', payload: JSON.stringify({ event: 'submission.created', submissionId: 'sub-6', candidateName: 'Diana Developer' }, null, 2) },
    { id: 'log-wh-2', webhookId: 'wh-1', timestamp: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(), status: 'Success', payload: JSON.stringify({ event: 'submission.created', submissionId: 'sub-7', candidateName: 'Alice Candidate' }, null, 2) },
    { id: 'log-wh-3', webhookId: 'wh-2', timestamp: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(), status: 'Success', payload: JSON.stringify({ event: 'submission.evaluated', submissionId: 'sub-1', score: 84 }, null, 2) },
    { id: 'log-wh-4', webhookId: 'wh-4', timestamp: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(), status: 'Failed', payload: JSON.stringify({ event: 'user.created', userId: 'user-4', error: 'Invalid API Key' }, null, 2) },
];
