
import { getSystemLogs } from "@/lib/api";
import { SystemLogList } from "./log-list";
import type { SystemLog } from '@/lib/types';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

export default async function SystemLogsPage() {
  const logs = await getSystemLogs();

  return (
    <div className="flex-1 space-y-4 p-8 pt-6">
      <div className="flex items-center justify-between space-y-2">
         <div>
            <h2 className="font-headline text-3xl font-bold tracking-tight">
                System Log Viewer
            </h2>
            <p className="text-muted-foreground">
                Browse and manage system logs from all services.
            </p>
        </div>
      </div>
      <Card>
        <CardHeader>
            <CardTitle>All System Logs</CardTitle>
            <CardDescription>
                A real-time feed of all logs generated by platform services.
            </CardDescription>
        </CardHeader>
        <CardContent>
            <SystemLogList initialData={logs} />
        </CardContent>
      </Card>
    </div>
  );
}
